package mibuscaminas;

import javax.swing.ImageIcon;

//Hecho por @Eda y @Valeria :3 con amorx
// translucido
//ESTA ES LA SEXTA VEZ QUE HACEMOS EL JUEGO >:'v

//Insert sufrimiento :'c
public class Buscaminas extends javax.swing.JFrame { 
       //Ibamos a agregar mas niveles :'v, por eso se llama nivel intermedio, pero no nos dio tiempo :(
        intermedio nivelIntermedio = new intermedio();
              
                //las imagencitas que van a aparecer al final
                private String[] archi = {"/imagenes/gano.png", "/imagenes/perdio.png", "/imagenes/nueva.png"};
        private ImageIcon[] ima = new ImageIcon[3]; 
       
        //Esto hace que aparezca toooooda la interfaz grafica,sin ella no se pintara nada, y abrira una ventana solita :c
        // Esto es el hermoso constructorcito
    public Buscaminas() {
        for(int i=0;i<3;i++){
            ima[i] = new ImageIcon(getClass().getResource(archi[i]));
        }
        //El nivelito
    	this.add(nivelIntermedio);
    	nivelIntermedio.setVisible(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        translucido = new org.edisoncor.gui.panel.PanelRectTranslucido();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mibuscaminas/Bundle"); // NOI18N
        setTitle(bundle.getString("Buscaminas.title")); // NOI18N

        translucido.setColorPrimario(new java.awt.Color(255, 0, 204));
        translucido.setColorSecundario(new java.awt.Color(51, 255, 153));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("Buscaminas.jLabel1.text")); // NOI18N

        jButton1.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jButton1.setText(bundle.getString("Buscaminas.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout translucidoLayout = new javax.swing.GroupLayout(translucido);
        translucido.setLayout(translucidoLayout);
        translucidoLayout.setHorizontalGroup(
            translucidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(translucidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(translucidoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        translucidoLayout.setVerticalGroup(
            translucidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(translucidoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(translucido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(translucido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //Este es el nivel intermedio, y todo esto llama a la clase Intermedio :3
        nivelIntermedio.btnreiniciar.setIcon(ima[2]);
        //Esto pinta las cosas en el tablero 
        nivelIntermedio.quitarBotonesIntermedio();     
        //Esto hace que aparezca el tablero :3, sin esto solo se ve el boton
        nivelIntermedio.nuevaPartidaIntermedio();
        //Esto hace que se haga visible el nivel intermedio
        nivelIntermedio.setVisible(true);  
        
        this.setVisible(false);
        this.setSize(418,484);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        jButton1.setVisible(false);
        translucido.setVisible(false);
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Buscaminas game = new Buscaminas();
                game.setLocationRelativeTo(null);
                game.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private org.edisoncor.gui.panel.PanelRectTranslucido translucido;
    // End of variables declaration//GEN-END:variables
}
